//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BandD.Serwis.Model.DictionariesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DictionariesService.IDictionariesService")]
    public interface IDictionariesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/Autorauthorization", ReplyAction="http://tempuri.org/IDictionariesService/AutorauthorizationResponse")]
        bool Autorauthorization(string password, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/Autorauthorization", ReplyAction="http://tempuri.org/IDictionariesService/AutorauthorizationResponse")]
        System.Threading.Tasks.Task<bool> AutorauthorizationAsync(string password, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/GetDataFromUser", ReplyAction="http://tempuri.org/IDictionariesService/GetDataFromUserResponse")]
        BandD.Serwis.ClassViewModel.Dictionaries.UserView[] GetDataFromUser(string name, System.Nullable<bool> status, System.Nullable<System.Guid> role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/GetDataFromUser", ReplyAction="http://tempuri.org/IDictionariesService/GetDataFromUserResponse")]
        System.Threading.Tasks.Task<BandD.Serwis.ClassViewModel.Dictionaries.UserView[]> GetDataFromUserAsync(string name, System.Nullable<bool> status, System.Nullable<System.Guid> role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/RemoveElementFromUsers", ReplyAction="http://tempuri.org/IDictionariesService/RemoveElementFromUsersResponse")]
        void RemoveElementFromUsers(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/RemoveElementFromUsers", ReplyAction="http://tempuri.org/IDictionariesService/RemoveElementFromUsersResponse")]
        System.Threading.Tasks.Task RemoveElementFromUsersAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/AddElementToUsers", ReplyAction="http://tempuri.org/IDictionariesService/AddElementToUsersResponse")]
        void AddElementToUsers(BandD.Serwis.ClassViewModel.Dictionaries.UserView element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/AddElementToUsers", ReplyAction="http://tempuri.org/IDictionariesService/AddElementToUsersResponse")]
        System.Threading.Tasks.Task AddElementToUsersAsync(BandD.Serwis.ClassViewModel.Dictionaries.UserView element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/UpdateElementUsers", ReplyAction="http://tempuri.org/IDictionariesService/UpdateElementUsersResponse")]
        void UpdateElementUsers(BandD.Serwis.ClassViewModel.Dictionaries.UserView element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/UpdateElementUsers", ReplyAction="http://tempuri.org/IDictionariesService/UpdateElementUsersResponse")]
        System.Threading.Tasks.Task UpdateElementUsersAsync(BandD.Serwis.ClassViewModel.Dictionaries.UserView element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/GetDataFromSlOrderStat", ReplyAction="http://tempuri.org/IDictionariesService/GetDataFromSlOrderStatResponse")]
        BandD.Serwis.ClassViewModel.Dictionaries.SlOrderStatView[] GetDataFromSlOrderStat(string name, System.Nullable<bool> activity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/GetDataFromSlOrderStat", ReplyAction="http://tempuri.org/IDictionariesService/GetDataFromSlOrderStatResponse")]
        System.Threading.Tasks.Task<BandD.Serwis.ClassViewModel.Dictionaries.SlOrderStatView[]> GetDataFromSlOrderStatAsync(string name, System.Nullable<bool> activity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/RemoveElementFromSlOrderStat", ReplyAction="http://tempuri.org/IDictionariesService/RemoveElementFromSlOrderStatResponse")]
        void RemoveElementFromSlOrderStat(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/RemoveElementFromSlOrderStat", ReplyAction="http://tempuri.org/IDictionariesService/RemoveElementFromSlOrderStatResponse")]
        System.Threading.Tasks.Task RemoveElementFromSlOrderStatAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/AddElementToSlOrderStat", ReplyAction="http://tempuri.org/IDictionariesService/AddElementToSlOrderStatResponse")]
        void AddElementToSlOrderStat(BandD.Serwis.ClassViewModel.Dictionaries.SlOrderStatView element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/AddElementToSlOrderStat", ReplyAction="http://tempuri.org/IDictionariesService/AddElementToSlOrderStatResponse")]
        System.Threading.Tasks.Task AddElementToSlOrderStatAsync(BandD.Serwis.ClassViewModel.Dictionaries.SlOrderStatView element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/UpdateElementSlOrderStat", ReplyAction="http://tempuri.org/IDictionariesService/UpdateElementSlOrderStatResponse")]
        void UpdateElementSlOrderStat(BandD.Serwis.ClassViewModel.Dictionaries.SlOrderStatView element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/UpdateElementSlOrderStat", ReplyAction="http://tempuri.org/IDictionariesService/UpdateElementSlOrderStatResponse")]
        System.Threading.Tasks.Task UpdateElementSlOrderStatAsync(BandD.Serwis.ClassViewModel.Dictionaries.SlOrderStatView element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/GetDataFromSlCarrierStat", ReplyAction="http://tempuri.org/IDictionariesService/GetDataFromSlCarrierStatResponse")]
        BandD.Serwis.ClassViewModel.Dictionaries.SlCarriersStatView[] GetDataFromSlCarrierStat(string name, System.Nullable<bool> carrierStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/GetDataFromSlCarrierStat", ReplyAction="http://tempuri.org/IDictionariesService/GetDataFromSlCarrierStatResponse")]
        System.Threading.Tasks.Task<BandD.Serwis.ClassViewModel.Dictionaries.SlCarriersStatView[]> GetDataFromSlCarrierStatAsync(string name, System.Nullable<bool> carrierStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/UpdateElementSlCarrierStat", ReplyAction="http://tempuri.org/IDictionariesService/UpdateElementSlCarrierStatResponse")]
        void UpdateElementSlCarrierStat(BandD.Serwis.ClassViewModel.Dictionaries.SlCarriersStatView stats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/UpdateElementSlCarrierStat", ReplyAction="http://tempuri.org/IDictionariesService/UpdateElementSlCarrierStatResponse")]
        System.Threading.Tasks.Task UpdateElementSlCarrierStatAsync(BandD.Serwis.ClassViewModel.Dictionaries.SlCarriersStatView stats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/AddElementToSlCarrierStat", ReplyAction="http://tempuri.org/IDictionariesService/AddElementToSlCarrierStatResponse")]
        void AddElementToSlCarrierStat(BandD.Serwis.ClassViewModel.Dictionaries.SlCarriersStatView stats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/AddElementToSlCarrierStat", ReplyAction="http://tempuri.org/IDictionariesService/AddElementToSlCarrierStatResponse")]
        System.Threading.Tasks.Task AddElementToSlCarrierStatAsync(BandD.Serwis.ClassViewModel.Dictionaries.SlCarriersStatView stats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/RemoveElementFromSlCarrierStat", ReplyAction="http://tempuri.org/IDictionariesService/RemoveElementFromSlCarrierStatResponse")]
        void RemoveElementFromSlCarrierStat(System.Guid statsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/RemoveElementFromSlCarrierStat", ReplyAction="http://tempuri.org/IDictionariesService/RemoveElementFromSlCarrierStatResponse")]
        System.Threading.Tasks.Task RemoveElementFromSlCarrierStatAsync(System.Guid statsId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/GetAllActiveRoles", ReplyAction="http://tempuri.org/IDictionariesService/GetAllActiveRolesResponse")]
        BandD.Serwis.ClassViewModel.Dictionaries.SlRoleView[] GetAllActiveRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDictionariesService/GetAllActiveRoles", ReplyAction="http://tempuri.org/IDictionariesService/GetAllActiveRolesResponse")]
        System.Threading.Tasks.Task<BandD.Serwis.ClassViewModel.Dictionaries.SlRoleView[]> GetAllActiveRolesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDictionariesServiceChannel : BandD.Serwis.Model.DictionariesService.IDictionariesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DictionariesServiceClient : System.ServiceModel.ClientBase<BandD.Serwis.Model.DictionariesService.IDictionariesService>, BandD.Serwis.Model.DictionariesService.IDictionariesService {
        
        public DictionariesServiceClient() {
        }
        
        public DictionariesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DictionariesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictionariesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DictionariesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Autorauthorization(string password, string userName) {
            return base.Channel.Autorauthorization(password, userName);
        }
        
        public System.Threading.Tasks.Task<bool> AutorauthorizationAsync(string password, string userName) {
            return base.Channel.AutorauthorizationAsync(password, userName);
        }
        
        public BandD.Serwis.ClassViewModel.Dictionaries.UserView[] GetDataFromUser(string name, System.Nullable<bool> status, System.Nullable<System.Guid> role) {
            return base.Channel.GetDataFromUser(name, status, role);
        }
        
        public System.Threading.Tasks.Task<BandD.Serwis.ClassViewModel.Dictionaries.UserView[]> GetDataFromUserAsync(string name, System.Nullable<bool> status, System.Nullable<System.Guid> role) {
            return base.Channel.GetDataFromUserAsync(name, status, role);
        }
        
        public void RemoveElementFromUsers(System.Guid id) {
            base.Channel.RemoveElementFromUsers(id);
        }
        
        public System.Threading.Tasks.Task RemoveElementFromUsersAsync(System.Guid id) {
            return base.Channel.RemoveElementFromUsersAsync(id);
        }
        
        public void AddElementToUsers(BandD.Serwis.ClassViewModel.Dictionaries.UserView element) {
            base.Channel.AddElementToUsers(element);
        }
        
        public System.Threading.Tasks.Task AddElementToUsersAsync(BandD.Serwis.ClassViewModel.Dictionaries.UserView element) {
            return base.Channel.AddElementToUsersAsync(element);
        }
        
        public void UpdateElementUsers(BandD.Serwis.ClassViewModel.Dictionaries.UserView element) {
            base.Channel.UpdateElementUsers(element);
        }
        
        public System.Threading.Tasks.Task UpdateElementUsersAsync(BandD.Serwis.ClassViewModel.Dictionaries.UserView element) {
            return base.Channel.UpdateElementUsersAsync(element);
        }
        
        public BandD.Serwis.ClassViewModel.Dictionaries.SlOrderStatView[] GetDataFromSlOrderStat(string name, System.Nullable<bool> activity) {
            return base.Channel.GetDataFromSlOrderStat(name, activity);
        }
        
        public System.Threading.Tasks.Task<BandD.Serwis.ClassViewModel.Dictionaries.SlOrderStatView[]> GetDataFromSlOrderStatAsync(string name, System.Nullable<bool> activity) {
            return base.Channel.GetDataFromSlOrderStatAsync(name, activity);
        }
        
        public void RemoveElementFromSlOrderStat(System.Guid id) {
            base.Channel.RemoveElementFromSlOrderStat(id);
        }
        
        public System.Threading.Tasks.Task RemoveElementFromSlOrderStatAsync(System.Guid id) {
            return base.Channel.RemoveElementFromSlOrderStatAsync(id);
        }
        
        public void AddElementToSlOrderStat(BandD.Serwis.ClassViewModel.Dictionaries.SlOrderStatView element) {
            base.Channel.AddElementToSlOrderStat(element);
        }
        
        public System.Threading.Tasks.Task AddElementToSlOrderStatAsync(BandD.Serwis.ClassViewModel.Dictionaries.SlOrderStatView element) {
            return base.Channel.AddElementToSlOrderStatAsync(element);
        }
        
        public void UpdateElementSlOrderStat(BandD.Serwis.ClassViewModel.Dictionaries.SlOrderStatView element) {
            base.Channel.UpdateElementSlOrderStat(element);
        }
        
        public System.Threading.Tasks.Task UpdateElementSlOrderStatAsync(BandD.Serwis.ClassViewModel.Dictionaries.SlOrderStatView element) {
            return base.Channel.UpdateElementSlOrderStatAsync(element);
        }
        
        public BandD.Serwis.ClassViewModel.Dictionaries.SlCarriersStatView[] GetDataFromSlCarrierStat(string name, System.Nullable<bool> carrierStatus) {
            return base.Channel.GetDataFromSlCarrierStat(name, carrierStatus);
        }
        
        public System.Threading.Tasks.Task<BandD.Serwis.ClassViewModel.Dictionaries.SlCarriersStatView[]> GetDataFromSlCarrierStatAsync(string name, System.Nullable<bool> carrierStatus) {
            return base.Channel.GetDataFromSlCarrierStatAsync(name, carrierStatus);
        }
        
        public void UpdateElementSlCarrierStat(BandD.Serwis.ClassViewModel.Dictionaries.SlCarriersStatView stats) {
            base.Channel.UpdateElementSlCarrierStat(stats);
        }
        
        public System.Threading.Tasks.Task UpdateElementSlCarrierStatAsync(BandD.Serwis.ClassViewModel.Dictionaries.SlCarriersStatView stats) {
            return base.Channel.UpdateElementSlCarrierStatAsync(stats);
        }
        
        public void AddElementToSlCarrierStat(BandD.Serwis.ClassViewModel.Dictionaries.SlCarriersStatView stats) {
            base.Channel.AddElementToSlCarrierStat(stats);
        }
        
        public System.Threading.Tasks.Task AddElementToSlCarrierStatAsync(BandD.Serwis.ClassViewModel.Dictionaries.SlCarriersStatView stats) {
            return base.Channel.AddElementToSlCarrierStatAsync(stats);
        }
        
        public void RemoveElementFromSlCarrierStat(System.Guid statsId) {
            base.Channel.RemoveElementFromSlCarrierStat(statsId);
        }
        
        public System.Threading.Tasks.Task RemoveElementFromSlCarrierStatAsync(System.Guid statsId) {
            return base.Channel.RemoveElementFromSlCarrierStatAsync(statsId);
        }
        
        public BandD.Serwis.ClassViewModel.Dictionaries.SlRoleView[] GetAllActiveRoles() {
            return base.Channel.GetAllActiveRoles();
        }
        
        public System.Threading.Tasks.Task<BandD.Serwis.ClassViewModel.Dictionaries.SlRoleView[]> GetAllActiveRolesAsync() {
            return base.Channel.GetAllActiveRolesAsync();
        }
    }
}
